apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/build-id: '3'
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
    fabric8.io/git-branch: release-v2.2.265
    fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/iconUrl: >-
      https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
  labels:
    expose: 'true'
    group: io.fabric8.devops.apps
    project: grafana
    provider: fabric8
    version: 2.2.265
  name: grafana
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    group: io.fabric8.devops.apps
    project: grafana
    provider: fabric8
endGroup: false
newGroup: false
