apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/build-id: '3'
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
    fabric8.io/git-branch: release-v2.2.273
    fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/iconUrl: >-
      https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
    fabric8.io/metrics-path: >-
      dashboard/file/kubernetes-pods.json/?var-project=grafana&var-version=2.2.273
  labels:
    group: io.fabric8.devops.apps
    project: grafana
    provider: fabric8
    version: 2.2.273
  name: grafana
spec:
  replicas: 1
  selector:
    group: io.fabric8.devops.apps
    project: grafana
    provider: fabric8
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/build-id: '3'
        fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
        fabric8.io/git-branch: release-v2.2.273
        fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/git-url: >-
          http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/iconUrl: >-
          https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
        fabric8.io/metrics-path: >-
          dashboard/file/kubernetes-pods.json/?var-project=grafana&var-version=2.2.273
      labels:
        group: io.fabric8.devops.apps
        project: grafana
        provider: fabric8
        version: 2.2.273
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 'fabric8/grafana:2.2.273'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 3000
            initialDelaySeconds: 5
          name: grafana
          readinessProbe:
            httpGet:
              port: 3000
            initialDelaySeconds: 5
          securityContext:
            privileged: false
  triggers:
    - type: ConfigChange
endGroup: false
newGroup: true
