apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/build-id: "3"
    fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/3
    fabric8.io/git-branch: release-v2.2.265
    fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=grafana&var-version=2.2.265
  creationTimestamp: null
  generation: 1
  labels:
    group: io.fabric8.devops.apps
    project: grafana
    provider: fabric8
    version: 2.2.265
  name: grafana
spec:
  replicas: 1
  selector:
    group: io.fabric8.devops.apps
    project: grafana
    provider: fabric8
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 10800
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/build-id: "3"
        fabric8.io/build-url: http://jenkins.ux.fabric8.io/job/oss-parent/3
        fabric8.io/git-branch: release-v2.2.265
        fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/git-url: http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana/src/main/fabric8/icon.png
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=grafana&var-version=2.2.265
      creationTimestamp: null
      labels:
        group: io.fabric8.devops.apps
        project: grafana
        provider: fabric8
        version: 2.2.265
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: fabric8/grafana:2.2.265
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: grafana
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 1
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
