apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/build-id: '3'
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
    fabric8.io/git-branch: release-v2.2.265
    fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
    fabric8.io/iconUrl: >-
      https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
    fabric8.io/metrics-path: >-
      dashboard/file/kubernetes-pods.json/?var-project=prometheus-blackbox-exporter&var-version=2.2.265
  labels:
    group: io.fabric8.devops.apps
    project: prometheus-blackbox-exporter
    provider: fabric8
    version: 2.2.265
  name: prometheus-blackbox-expo
spec:
  replicas: 1
  selector:
    group: io.fabric8.devops.apps
    project: prometheus-blackbox-exporter
    provider: fabric8
  strategy:
    rollingParams:
      timeoutSeconds: 10800
    type: Rolling
  template:
    metadata:
      annotations:
        fabric8.io/build-id: '3'
        fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/3'
        fabric8.io/git-branch: release-v2.2.265
        fabric8.io/git-commit: 3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/git-url: >-
          http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/3ed46620b6802ae12c469284f09cf8b799d88411
        fabric8.io/iconUrl: >-
          https://cdn.rawgit.com/fabric8io/fabric8-devops/master/prometheus-blackbox-exporter/src/main/fabric8/icon.png
        fabric8.io/metrics-path: >-
          dashboard/file/kubernetes-pods.json/?var-project=prometheus-blackbox-exporter&var-version=2.2.265
      labels:
        group: io.fabric8.devops.apps
        project: prometheus-blackbox-exporter
        provider: fabric8
        version: 2.2.265
    spec:
      containers:
        - image: 'prom/blackbox-exporter:master'
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 1
          name: blackbox-exporter
          ports:
            - containerPort: 9115
              name: http
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 1
          volumeMounts:
            - mountPath: /etc/blackbox_exporter
              name: config-volume
      volumes:
        - configMap:
            name: blackbox-exporter
          name: config-volume
  triggers:
    - type: ConfigChange
endGroup: true
newGroup: false
